import Head from 'next/head';
import Navbar from '../components/Navbar';
import Stories from '../components/Stories';

export default function Home() {
  return (
    <>
      <Head>
        <title>Semina || Stories</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='bg-navy'>
      <Navbar />
      </header>
      <Stories/>
    </>
  );
}